site_name: studious-octo-funicular-ui
repo_url: https://github.com/Andrewtham/studious-octo-funicular-ui
site_url: https://Andrewtham.github.io/studious-octo-funicular-ui
site_description: UI for Narrative Analysis
site_author: Andrew Tham
edit_uri: edit/main/docs/
repo_name: Andrewtham/studious-octo-funicular-ui
copyright: Maintained by <a href="https://Andrewtham.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Andrewtham/studious-octo-funicular-ui
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/studious-octo-funicular-ui

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
